version: '2.3'
services:
    anaconda_gpu:
        build: .
        volumes:
            - ./:/workspace
            - "/home/daichi/Dropbox/data/keyakizaka_mining:/keyakizaka_mining"
        runtime: nvidia
        ports:
            - "8899:8899"
